<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="RR">

<!-- Defining macros -->
<xacro:property name="box_X" value="0.2" />
<xacro:property name="box_Y" value="0.2" />
<xacro:property name="box_Z" value="0.5" />

<!-- Actuator -->
<xacro:property name="actuator_total_width" value="0.05708" />
<xacro:property name="actuator_diameter" value="0.1031" />

<xacro:property name="bodylen" value="1" />
<xacro:property name="height" value="0.1" />
<xacro:property name="offset" value="0.1" />
<xacro:property name="base_height" value="1" />

<!-- Moment of inertia -->
<xacro:macro name="default_inertial" params="mass xl yl zl *Dorigin">
    <inertial>
            <mass value="${mass}" />
            <inertia ixx="${ mass * ( yl*yl + zl*zl ) / 12 }" ixy="0.0" ixz="0.0"
                     iyy="${ mass * ( xl*xl + zl*zl ) / 12 }" iyz="0.0"
                     izz="${ mass * ( yl*yl + xl*xl ) / 12 }" />
            <xacro:insert_block name="Dorigin" />
    </inertial>
</xacro:macro>

<material name="blue">
  <color rgba="0 0 0.8 1"/>
</material>

<material name="red">
  <color rgba="0.8 0 0 1"/>
</material>

<!-- Addin objects: -->

<link name="world"/> 

 <joint name="world_joint" type="fixed">
  <parent link="world"/>
  <child link="base_link"/>
  <origin rpy="0 ${-pi/2} ${-pi/2}" xyz="0 0 ${box_Z}"/>
</joint> 

<!-- <link name="base_link">
  <visual>
    <geometry>
      <box size="${box_X} ${box_Y} ${box_Z}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 ${-box_Z/2}"/>
    <material name="blue"/>
  </visual>
  <collision>
    <geometry>
      <box size="${box_X} ${box_Y} ${box_Z}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 ${-box_Z/2}"/>
  </collision> 
  <inertial>
    <mass value="100" />
    <inertia ixx="0.0100" ixy="0.0" ixz="0.0"
              iyy="0.0100" iyz="0.0"
              izz="0.0100" />
    <origin rpy="0 0 0" xyz="0 0 ${-base_height/2}"/>
  </inertial> 
</link>
 -->

<!-- Link 1  -->
<link name="base_link">
  <visual>
    <geometry>      
        <mesh scale=".001 .001 .001" filename="package://leg_description/meshes/link2stl.STL" />
    </geometry>
    <origin rpy="0 0 0" xyz="${-actuator_diameter/2} ${-actuator_diameter/2} 0"/>
    <!-- <origin rpy="0 ${-pi/2} ${-pi/2}" xyz="0 0 0"/> -->
    <material name="red"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${actuator_diameter}" length="${actuator_total_width}"/>
    </geometry>
    <origin rpy="${pi/2} 0 ${-pi/2}" xyz="0 0 0"/>
  </collision>
  <xacro:default_inertial mass="10" xl="1" yl="1" zl="1">
    <origin rpy="0 0 0" xyz="0 0 0" />
  </xacro:default_inertial>
</link>
  

<!-- Link 1  -->
<!-- <link name="link1">
  <visual>
    <geometry>      
        <mesh scale=".001 .001 .001" filename="package://leg_description/meshes/link2stl.STL" />
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <origin rpy="0 ${-pi/2} ${-pi/2}" xyz="0 0 0"/>
    <material name="red"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${actuator_diameter}" length="${actuator_total_width}"/>
    </geometry>
    <origin rpy="${pi/2} 0 ${-pi/2}" xyz="0 0 0"/>
  </collision>
  <xacro:default_inertial mass="10" xl="1" yl="1" zl="1">
    <origin rpy="0 0 0" xyz="0 0 0" />
  </xacro:default_inertial>
</link>

<joint name="base_to_link1" type="continuous"> 
  <parent link="base_link"/>
  <child link="link1"/>
  <axis rpy = "0 0 0" xyz="0 0 1"/>
  <origin rpy = "0 0 0" xyz="0 0 ${actuator_total_width/2}"/>
</joint>   -->

</robot>